#ifndef _GLOBALS_H
#define _GLOBALS_H

#define ASCII_0 48
#define ASCII_1 49
#define ASCII_2 50
#define ASCII_3 51
#define ASCII_4 52
#define ASCII_5 53

#define SIZE_X 40
#define SIZE_Y 24

#define CARD_ADDRESS 0xC200
#define APPLE_COMMAND_ADDRESS 0xC201
#define RAM_DATA_START_ADDRESS 0xC202

#define APP_ID 200

#define COMMAND_SET_COUNTRY 20
#define COMMAND_SET_CITY 21
#define COMMAND_FETCH_WEATHER 25

#define DEFAULT_COUNTRY_CODE "US"

#endif
